"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.once = exports.paystack = exports.flutterwave = void 0;
const paystack_sdk_1 = require("paystack-sdk");
const flutterwave_1 = require("./flutterwave");
const dotenv_1 = require("dotenv");
const once_1 = require("./once");
(0, dotenv_1.config)();
exports.flutterwave = new flutterwave_1.Flutterwave();
exports.paystack = new paystack_sdk_1.Paystack(process.env.PAYSTACK_SECRET_KEY);
exports.once = new once_1.Once();
